<Project>

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <SelfContained>false</SelfContained>
        <DebugType>embedded</DebugType>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">win-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">linux-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64' ">linux-arm64</RuntimeIdentifier>
        <PublishDir>..\out-$(RuntimeIdentifier)\plugins\$(MSBuildProjectName)\</PublishDir>
        <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputPath>..\AssettoServer\bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\plugins\$(MSBuildProjectName)</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AssettoServer.Shared\AssettoServer.Shared.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </ProjectReference>
        <ProjectReference Include="..\AssettoServer\AssettoServer.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="wwwroot\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
