<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">win-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">linux-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64' ">linux-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <RedistFiles Include="Redist\$(RuntimeIdentifier)\*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.15.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="CopyRedistFilesOnBuild" AfterTargets="AfterBuild">
        <Copy SourceFiles="@(RedistFiles)" DestinationFolder="$(OutDir)" />
    </Target>

    <ItemGroup>
      <ProjectReference Include="..\AssettoServer.Shared\AssettoServer.Shared.csproj" />
      <ProjectReference Include="..\AssettoServer\AssettoServer.csproj" />
      <ProjectReference Include="..\AutoModerationPlugin\AutoModerationPlugin.csproj" />
      <ProjectReference Include="..\FastTravelPlugin\FastTravelPlugin.csproj" />
      <ProjectReference Include="..\ReplayPlugin\ReplayPlugin.csproj" />
      <ProjectReference Include="..\TagModePlugin\TagModePlugin.csproj" />
      <ProjectReference Include="..\VotingPresetPlugin\VotingPresetPlugin.csproj" />
    </ItemGroup>

</Project>
