<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">win-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">linux-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64' ">linux-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Redist\$(RuntimeIdentifier)\*" CopyToOutputDirectory="PreserveNewest" TargetPath="%(Filename)%(Extension)" />
        <None Include="..\AssettoServer\Assets\checksums_remote.json" CopyToOutputDirectory="PreserveNewest" TargetPath="content\checksums_remote.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit3TestAdapter"/>
        <PackageReference Include="NUnit.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AssettoServer.Shared\AssettoServer.Shared.csproj" />
      <ProjectReference Include="..\AssettoServer\AssettoServer.csproj" />      <ProjectReference Include="..\ChecksumUtils\ChecksumUtils.csproj" />
      <ProjectReference Include="..\Plugins\AutoModerationPlugin\AutoModerationPlugin.csproj" />
      <ProjectReference Include="..\Plugins\FastTravelPlugin\FastTravelPlugin.csproj" />
      <ProjectReference Include="..\Plugins\TagModePlugin\TagModePlugin.csproj" />
      <ProjectReference Include="..\Plugins\VotingPresetPlugin\VotingPresetPlugin.csproj" />
    </ItemGroup>

</Project>
