<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <PublishSingleFile Condition="'$(NO_SINGLE_FILE)' != '1'">true</PublishSingleFile>
        <SelfContained Condition="'$(Configuration)' == 'Release'">true</SelfContained>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <DebugType>embedded</DebugType>
        <Nullable>enable</Nullable>
        <PublishDir>..\out-$(RuntimeIdentifier)\</PublishDir>
        <NoWarn>ERP022,EPC12,EPC20</NoWarn>
        <Platforms>AnyCPU</Platforms>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">win-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">linux-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64' ">linux-arm64</RuntimeIdentifier>
        <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
        <InvariantGlobalization>true</InvariantGlobalization>
        <ApplicationIcon>Assets/assettoserver.ico</ApplicationIcon>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Features>runtime-async=on</Features>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AssettoServer.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Autofac.Extensions.DependencyInjection"/>
        <PackageReference Include="CommandLineParser"/>
        <PackageReference Include="CommunityToolkit.Common"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="DotNext.IO"/>
        <PackageReference Include="DotNext.Unsafe"/>
        <PackageReference Include="ErrorProne.NET.CoreAnalyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ErrorProne.NET.Structs">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="Humanizer.Core"/>
        <PackageReference Include="ini-parser">
            <NoWarn>NU1701</NoWarn>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="McMaster.NETCore.Plugins"/>
        <PackageReference Include="NJsonSchema"/>
        <PackageReference Include="NodaTime"/>
        <PackageReference Include="Open.NAT">
            <NoWarn>NU1701</NoWarn>
        </PackageReference>
        <PackageReference Include="Polly"/>
        <PackageReference Include="prometheus-net"/>
        <PackageReference Include="prometheus-net.AspNetCore"/>
        <PackageReference Include="protobuf-net.Grpc"/>
        <PackageReference Include="Qmmands"/>
        <PackageReference Include="Scriban"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Enrichers.Environment"/>
        <PackageReference Include="Serilog.Enrichers.Sensitive"/>
        <PackageReference Include="Serilog.Expressions"/>
        <PackageReference Include="Serilog.Sinks.Async"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="Serilog.Sinks.Grafana.Loki"/>
        <PackageReference Include="SerilogTimings"/>
        <PackageReference Include="compujuckel.Facepunch.Steamworks"/>
        <PackageReference Include="compujuckel.Supercluster.KDTree"/>
        <PackageReference Include="Sigil"/>
        <PackageReference Include="SunCalcNet"/>
        <PackageReference Include="System.IO.Hashing"/>
        <PackageReference Include="YamlDotNet"/>
        <PackageReference Include="MinVer">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <PropertyGroup>
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <MinVerIgnoreHeight>true</MinVerIgnoreHeight>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AssettoServer.Shared\AssettoServer.Shared.csproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Server\Ai\ai_debug.lua"/>
        <EmbeddedResource Include="Server\Ai\ai_debug.lua"/>
        <None Remove="Server\Lua\assettoserver.lua"/>
        <EmbeddedResource Include="Server\Lua\assettoserver.lua"/>
        <None Remove="Assets\logo_42.png"/>
        <EmbeddedResource Include="Assets\logo_42.png"/>
        <None Remove="Assets\srp-logo-new.png"/>
        <EmbeddedResource Include="Assets\srp-logo-new.png"/>
        <None Remove="Assets\crash_report.md.tpl"/>
        <EmbeddedResource Include="Assets\crash_report.md.tpl"/>
        <None Remove="Assets\server_cfg.ini"/>
        <EmbeddedResource Include="Assets\server_cfg.ini"/>
        <None Remove="Assets\entry_list.ini"/>
        <EmbeddedResource Include="Assets\entry_list.ini"/>
        <Content Update="Assets\checksums_ks.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>content\checksums_ks.json</TargetPath>
        </Content>

        <None Update="wwwroot\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>

        <None Update="Assets\steam_appid.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>steam_appid.txt</TargetPath>
        </None>
    </ItemGroup>
</Project>
