using System.IO;
using System.Numerics;
using AssettoServer.Utils;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.ObjectGraphVisitors;

namespace AssettoServer.Server.Configuration;

public static class ReferenceConfigurationHelper
{
    private const string BaseFolder = "cfg/reference";
    
    public static void WriteReferenceConfiguration(string filename, string schemaPath, object config, string name)
    {
        Directory.CreateDirectory(BaseFolder);
        
        var path = Path.Join(BaseFolder, filename);
        
        using var writer = File.CreateText(path);
        ConfigurationSchemaGenerator.WriteModeLine(writer, BaseFolder, schemaPath);
        writer.WriteLine($"# {name} Reference Configuration");
        writer.WriteLine("# This file serves as an overview of all possible options.");
        writer.WriteLine("# DO NOT EDIT THIS FILE - It will be overwritten on server restart.");
        writer.WriteLine();

        var builder = new SerializerBuilder()
            .WithEventEmitter(next => new YamlFlowStyleEmitter<Vector3>(next))
            .WithoutEmissionPhaseObjectGraphVisitor<DefaultValuesObjectGraphVisitor>()
            .Build();
            
        builder.Serialize(writer, config);
    }
}
